---

# ---- Jekyll Configuration ----
port: 4000
host: '0.0.0.0'
safe: false
exclude: ['CNAME', 'README.md', '.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE']
permalink: '/'
timezone: 'America/New_York'
lsi: false
markdown: 'kramdown'
highlighter: 'pygments'

# ---- Site configuration ----
domain:      'http://nickjj.github.io'
google_ua:   ''
form_action:  '//forms.brace.io/nick.janetakis@gmail.com'
phone_number: '(631) 397-0522'
title:       'Nick Janetakis - Full stack developer and marketing strategist'
keywords:    'development, website, consulting, system admin, automation,
              marketing, entrepreneur'
description: 'Looking to create a website or start a store? How about gaining and retaining more customers? Perhaps you want custom software? Learn how I can help you.'

colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#63BD2F'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
